---
- name: Ensure snap is installed
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: true

- name: Install microk8s via snap
  ansible.builtin.command: snap install microk8s --classic
  args:
    creates: /snap/bin/microk8s

- name: Add user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: true

# - name: Ensure kubectl can be run without sudo
#  ansible.builtin.command: chown -R "{{ ansible_user }}":"{{ ansible_user }}" /home/{{ ansible_user }}/.kube
#  ignore_errors: true
