services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/serial/by-id:/dev/serial/by-id
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    privileged: true
    restart: unless-stopped
