services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  airflow-base: &airflow-base
    image: ${AIRFLOW_IMAGE_NAME}
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: always

  scheduler:
    <<: *airflow-base
    container_name: airflow-scheduler
    command: scheduler

  webserver:
    <<: *airflow-base
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"

volumes:
  postgres_data:
