services:
  wg-easy:
    container_name: wireguard
    image: weejewel/wg-easy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PASSWORD=${WG_PASSWORD}
      - WG_HOST=${WG_HOST}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_AUTO_UPDATE=false
    volumes:
      - ./etc/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
