---
- name: Run Portainer on Raspberry Pi
  hosts: rpi4-1
  become: true
  tasks:

    - name: Ensure Home Assistant config folder exists
      ansible.builtin.file:
        path: /home/admin/home-assistant-config
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Run Home Assistant container
      community.docker.docker_container:
        name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        state: started
        restart_policy: unless-stopped
        network_mode: host
        privileged: yes
        volumes:
          - "/home/admin/home-assistant-config:/config"
          - "/etc/localtime:/etc/localtime:ro"
          - "/run/dbus:/run/dbus:ro"
        devices:
          - "/dev/ttyAMA0:/dev/ttyAMA0"
          - "/dev/serial/by-id:/dev/serial/by-id"
          - "/dev/bus/usb:/dev/bus/usb"

    - name: Check if HACS folder exists
      ansible.builtin.stat:
        path: /home/admin/home-assistant-config/custom_components/hacs
      register: hacs_folder

    - name: Install HACS in Home Assistant container if missing
      ansible.builtin.command: >
        docker exec home-assistant /bin/bash -c "wget -O - https://get.hacs.xyz | bash"
      when: not hacs_folder.stat.exists

    - name: Restart Home Assistant container
      community.docker.docker_container:
        name: home-assistant
        state: started
        restart: true
