---
- name: Run Home Assistant container
  hosts: rpi4-1
  become: true

  vars:
    project_src: /home/admin/docker/home-assistant

  tasks:
    - name: Ensure project source directory exists
      ansible.builtin.file:
        path: "{{ project_src }}"
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy docker-compose.yml to project source directory
      ansible.builtin.copy:
        src: ../../docker/home-assistant/docker-compose.yml
        dest: "{{ project_src }}/docker-compose.yml"
        owner: admin
        group: admin
        mode: '0644'

    - name: Pull latest image
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        pull: missing

    - name: Start container
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        state: present

    - name: Check if HACS is installed
      ansible.builtin.stat:
        path: "{{ project_src }}/config/custom_components/hacs"
      register: hacs_folder

    - name: Install HACS
      ansible.builtin.command: >
        docker exec home-assistant /bin/bash -c "wget -O - https://get.hacs.xyz | bash"
      when: not hacs_folder.stat.exists

    - name: Restart Home Assistant container
      community.docker.docker_container:
        name: home-assistant
        state: started
        restart: true
      when: not hacs_folder.stat.exists
