---
- name: Run Home Assistant container on Raspberry Pi
  hosts: rpi4-1
  become: true

  vars:
    docker_compose_path: /home/admin/docker-compose/home-assistant

  tasks:
    - name: Ensure compose project directory exists
      ansible.builtin.file:
        path: "{{ docker_compose_path }}"
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy docker-compose.yml to Pi
      ansible.builtin.copy:
        src: ../../docker/home-assistant/docker-compose.yml
        dest: "{{ docker_compose_path }}/docker-compose.yml"
        owner: admin
        group: admin
        mode: '0644'

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        pull: missing

    - name: Start containers using docker-compose
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_path }}"
        state: present

    - name: Check if HACS folder exists
      ansible.builtin.stat:
        path: /home/admin/home-assistant-config/custom_components/hacs
      register: hacs_folder

    - name: Install HACS in Home Assistant container if missing
      ansible.builtin.command: >
        docker exec home-assistant /bin/bash -c "wget -O - https://get.hacs.xyz | bash"
      when: not hacs_folder.stat.exists

    - name: Restart Home Assistant container
      community.docker.docker_container:
        name: home-assistant
        state: started
        restart: true
