---
- name: Run Postgres container
  hosts: rpi4-1
  become: true

  vars:
    project_src: /home/admin/docker/postgres
    postgres_network: postgres_network

  tasks:
    - name: Ensure project source directory exists
      ansible.builtin.file:
        path: "{{ project_src }}"
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy .env file
      ansible.builtin.copy:
        src: ../../docker/postgres/.env
        dest: "{{ project_src }}/.env"
        owner: admin
        group: admin
        mode: '0600'

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../../docker/postgres/docker-compose.yml
        dest: "{{ project_src }}/docker-compose.yml"
        owner: admin
        group: admin
        mode: '0644'

    - name: Copy initdb scripts
      ansible.builtin.copy:
        src: ../../docker/postgres/initdb/
        dest: "{{ project_src }}/initdb/"
        owner: admin
        group: admin
        mode: '0755'
        recurse: yes

    - name: Create Postgres network
      community.docker.docker_network:
        name: "{{ postgres_network }}"
        state: present
        scope: local
        internal: false

    - name: Start Postgres
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        state: present
        pull: missing
