ssh:
	ssh admin@192.168.0.105

portainer:
	ansible-playbook -i inventory.ini playbooks/portainer.yml

pypi-server:
	ansible-playbook -i inventory.ini playbooks/pypi-server.yml

home-assistant:
	ansible-playbook -i inventory.ini playbooks/home-assistant.yml

wireguard:
	ansible-playbook -i inventory.ini playbooks/wireguard.yml
