name: Publish Wheel

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  publish-wheel:
    name: Build & Publish Python Wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build Wheel
        run: |
          uv build --wheel

      - name: Publish Wheel to GitLab
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.GL_TOKEN }}
        run: |
          uv publish --index gitlab
