name: Push Image

on:
  pull_request:
    branches:
      - main
#    paths:
#      - 'airflow/Dockerfile'
#      - 'airflow/entrypoint.sh'
  workflow_dispatch:

jobs:
  push-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        working-directory: ./vars
        run: source .env.prd

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${GL_REGISTRY}
          username: __token__
          password: ${{ secrets.GL_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${GL_REGISTRY}/airflow

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
