name: Upload Wheel

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  upload-wheel:
    name: Build & Upload Python Wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        working-directory: ./vars
        run: source .env.prd

      - name: Install uv
        run: pip install uv

      - name: Update Azure CLI
        run: az upgrade --yes

      - name: Build Python Wheel
        run: |
          uv build --wheel
          WHEEL_NAME=$(basename dist/*.whl)
          echo "WHEEL_NAME=$WHEEL_NAME" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_SP_AF_CREDENTIALS }}

      - name: Upload Latest Wheel to PyPI
        run: |
          az storage blob upload \
            --account-name $PYPI_SA \
            --container-name $PYPI_CONTAINER \
            --file dist/$WHEEL_NAME \
            --name simple/airflow/$WHEEL_NAME \
            --overwrite \
            --auth-mode login

      - name: Batch Download PyPI
        run: |
          mkdir -p temp && \
          az storage blob download-batch \
            --account-name $PYPI_SA \
            --source $PYPI_CONTAINER \
            --destination temp \
            --pattern "*.whl" \
            --auth-mode login

      - name: Refresh PyPI Index
        run: uv run scripts/make_index.py

      - name: Batch Upload PyPI
        run: |
          az storage blob upload-batch \
              --account-name $PYPI_SA \
              --source temp \
              --destination $PYPI_CONTAINER \
              --overwrite \
              --auth-mode login
