name: Validate Code

on:
  pull_request:
    branches:
      - main

jobs:
  validate-code:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        working-directory: ./vars
        run: source .env.prd

      - name: Install uv
        run: pip install uv

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: $TF_VERSION

      - name: Install Workflow Dependencies
        run: uv sync --group workflow

      - name: Run Pre-commit Hooks
        run: uv run pre-commit run --all-files

      - name: Run Tests
        run: uv run pytest
