name: Validate Code

on:
  pull_request:
    branches:
      - main

jobs:
  ci-tests:
    name: Lint, Format & Type Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install Dependencies
        run: uv sync --group workflow

      - name: Lint Check
        run: uv run ruff check .

      - name: Format Check
        run: uv run ruff format --check .

      - name: Run Tests
        run: uv run pytest
