name: Validate Code

on:
  pull_request:
    branches:
      - main

jobs:
  ci-tests:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Sync System Environment
        run: brew bundle

      - name: Load Configuration
        run: source config/.env.shared

      - name: Install Workflow Dependencies
        run: uv sync --group workflow

      - name: Run Pre-commit Hooks
        run: uv run pre-commit run --all-files

      - name: Run Tests
        run: uv run pytest
